name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3 python3-pip python3-setuptools python3-virtualenv build-essential
        pip3 install --upgrade Cython buildozer

    - name: Build APK
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        yes | buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: math-duel-apk
        path: bin/*.apk